spring.datasource.url=jdbc:herddb:server:localhost:7000?server.start=true&server.base.dir=/pulsar-manager/data/dbdata
spring.datasource.schema=classpath:/META-INF/sql/herddb-schema.sql
spring.datasource.username=sa
spring.datasource.password=hdb
