plugins {
	id 'java-platform'
	id 'com.codelab.gradle'
}

group = 'com.codelab'
version = '1.0.0'
description = 'Codelab BOM'

javaPlatform {
	allowDependencies()
}

def springBootVersion = '4.1.1'
def codelabVersion = '1.0.0'
def lombokVersion = '1.18.46'

dependencies {
	api platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
	constraints {
		api "com.codelab:codelab-commons:${codelabVersion}"
		api "org.projectlombok:lombok:${lombokVersion}"
		api "com.codelab:codelab-commons:${codelabVersion}"
		api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.1'
	}
}
