plugins {
	id 'java-library'
	id 'com.codelab.gradle'
}

group = 'com.codelab'
version = '1.0.0'
description = 'Codelab Orders'


dependencies {
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	implementation platform('com.codelab:codelab-bom:1.0.0')
	annotationProcessor platform('com.codelab:codelab-bom:1.0.0')
	testAnnotationProcessor platform('com.codelab:codelab-bom:1.0.0')
	implementation 'com.codelab:codelab-commons:1.0.0'

	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-pulsar'


	testImplementation platform('org.junit:junit-bom:6.0.0')
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
	useJUnitPlatform()
}
